from .consultas import * 
from .documentos_identificativos import * 
from .especialidades import * 
from .medicos import * 
from .pacientes import * 
from .reviews import * 
from .turnos import * 
from .user_roles import * 
from .users import * 
from .turnos import * 