"""{MSG}

Revision ID: 12d3b8370d92
Revises: cd69839c4cf3
Create Date: 2025-11-02 11:31:07.020073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d3b8370d92'
down_revision: Union[str, Sequence[str], None] = 'cd69839c4cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__consultas__id_tu__6A30C649'), 'consultas', type_='foreignkey')
    op.create_foreign_key(None, 'consultas', 'turnos', ['id_turno'], ['id_turno'], ondelete='Cascade')
    op.drop_constraint(op.f('FK__medicos__id_user__5629CD9C'), 'medicos', type_='foreignkey')
    op.create_foreign_key(None, 'medicos', 'users', ['id_user'], ['id_user'], ondelete='CASCADE')
    op.drop_constraint(op.f('FK__pacientes__id_us__5EBF139D'), 'pacientes', type_='foreignkey')
    op.create_foreign_key(None, 'pacientes', 'users', ['id_user'], ['id_user'], ondelete='CASCADE')
    op.drop_constraint(op.f('FK__turnos__id_medic__656C112C'), 'turnos', type_='foreignkey')
    op.create_foreign_key(None, 'turnos', 'medicos', ['id_medico'], ['id_medico'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turnos', type_='foreignkey')
    op.create_foreign_key(op.f('FK__turnos__id_medic__656C112C'), 'turnos', 'medicos', ['id_medico'], ['id_medico'])
    op.drop_constraint(None, 'pacientes', type_='foreignkey')
    op.create_foreign_key(op.f('FK__pacientes__id_us__5EBF139D'), 'pacientes', 'users', ['id_user'], ['id_user'])
    op.drop_constraint(None, 'medicos', type_='foreignkey')
    op.create_foreign_key(op.f('FK__medicos__id_user__5629CD9C'), 'medicos', 'users', ['id_user'], ['id_user'])
    op.drop_constraint(None, 'consultas', type_='foreignkey')
    op.create_foreign_key(op.f('FK__consultas__id_tu__6A30C649'), 'consultas', 'turnos', ['id_turno'], ['id_turno'])
    # ### end Alembic commands ###
