"""{MSG}

Revision ID: 83cc2b295858
Revises: b384e0c6a975
Create Date: 2025-12-19 09:58:35.104792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83cc2b295858'
down_revision: Union[str, Sequence[str], None] = 'b384e0c6a975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "UQ__medicos__3A2E8FB1D6419A2B",
        "medicos",
        type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
