"""{MSG}

Revision ID: b384e0c6a975
Revises: dc9b515ca7c6
Create Date: 2025-12-19 09:56:13.951529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b384e0c6a975'
down_revision: Union[str, Sequence[str], None] = 'dc9b515ca7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_medicos_documento_identificacion'), 'medicos', ['documento_identificacion'], unique=False)
    op.create_index(op.f('ix_medicos_especialidad'), 'medicos', ['especialidad'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicos_especialidad'), table_name='medicos')
    op.drop_index(op.f('ix_medicos_documento_identificacion'), table_name='medicos')
    # ### end Alembic commands ###
