"""{MSG}

Revision ID: c1d86b167e67
Revises: 441f804eb1dd
Create Date: 2025-11-01 20:02:48.975950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d86b167e67'
down_revision: Union[str, Sequence[str], None] = '441f804eb1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('is_used', sa.Boolean(), nullable=False))
    op.add_column('refresh_token', sa.Column('valid_until', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_token', 'valid_until')
    op.drop_column('refresh_token', 'is_used')
    # ### end Alembic commands ###
