"""{MSG}

Revision ID: c25da9919989
Revises: 12d3b8370d92
Create Date: 2025-11-02 11:36:57.445447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c25da9919989'
down_revision: Union[str, Sequence[str], None] = '12d3b8370d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicos', sa.Column('img_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pacientes', sa.Column('img_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'img_name')
    op.drop_column('medicos', 'img_name')
    # ### end Alembic commands ###
