"""{MSG}

Revision ID: c97363593465
Revises: 54c91789ea4e
Create Date: 2025-12-18 21:16:54.702142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97363593465'
down_revision: Union[str, Sequence[str], None] = '54c91789ea4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_turnos_opciones',
    sa.Column('id_turnos_opciones', sa.Integer(), nullable=False),
    sa.Column('valor', sa.CHAR(length=2), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_turnos_opciones')
    )
    op.create_table('estados_turnos',
    sa.Column('id_estado_turno', sa.Integer(), nullable=False),
    sa.Column('id_turno', sa.Integer(), nullable=False),
    sa.Column('id_turnos_opciones', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_turno'], ['turnos.id_turno'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_turnos_opciones'], ['estados_turnos_opciones.id_turnos_opciones'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_estado_turno')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estados_turnos')
    op.drop_table('estados_turnos_opciones')
    # ### end Alembic commands ###
