"""{MSG}

Revision ID: cd69839c4cf3
Revises: c1d86b167e67
Create Date: 2025-11-02 10:50:49.294245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd69839c4cf3'
down_revision: Union[str, Sequence[str], None] = 'c1d86b167e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicos', sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('medicos', sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('pacientes', sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('pacientes', sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.drop_constraint(op.f('FK__pacientes__espec__5DCAEF64'), 'pacientes', type_='foreignkey')
    op.drop_constraint(op.f('UQ__paciente__30962D15B96F767A'), 'pacientes', type_='unique')
    op.drop_constraint(op.f('UQ__paciente__3A2E8FB199E4FA9D'), 'pacientes', type_='unique')
    op.drop_column('pacientes', 'matricula')
    op.drop_column('pacientes', 'especialidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('especialidad', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pacientes', sa.Column('matricula', sa.VARCHAR(length=200, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('FK__pacientes__espec__5DCAEF64'), 'pacientes', 'especialidades', ['especialidad'], ['id_especialidad'])
    op.drop_column('pacientes', 'apellido')
    op.drop_column('pacientes', 'nombre')
    op.drop_column('medicos', 'apellido')
    op.drop_column('medicos', 'nombre')
    # ### end Alembic commands ###
