"""{MSG}

Revision ID: dc9b515ca7c6
Revises: c97363593465
Create Date: 2025-12-18 22:53:49.486313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9b515ca7c6'
down_revision: Union[str, Sequence[str], None] = 'c97363593465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turnos', sa.Column('clasificacion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turnos', 'clasificacion')
    # ### end Alembic commands ###
